name: "Use Dependencies"

description: "Checks if the Go binaries have been cached with the hash of the all the Makefile."

runs:
  using: "composite"
  steps:
    - name: "🦫 Setup Golang"
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.22.6'
    - name: "💾 Cache dependencies"
      uses: actions/cache@v4
      id: cache-dependencies
      with:
        path: |
          $GOPATH/bin
        key: ${{ runner.os }}-go-${{ hashFiles('Makefile') }}
    - name: "📦 Install"
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: make install
      shell: bash
